version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19"
      FORGEVERSION: "41.1.0"
      TYPE: FORGE
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      TANGIA_ENV: STAGING
      TANGIA_GAME_ID: game_aaniPhdMIRffFYKPBNtMtA
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./docker-data/:/data/
      - ./build/libs/:/data/mods/
